future: true
permalink: /:title/
url: https://qazasdedc.github.io
name: Dragon Boy
author: Boy Dragon
qq: 435191784
email: 435191784@qq.com

duoshuo: qazasdedc
beian: 
cnzz: 
weibo: 
github: QAZASDEDC
about: "这里是子龙的个人博客，创建于 2018 年。"

safe: true
paginate: 20
